// Tag group configuration for the ideas index page.
// Order of groups controls render order.
// Order within a group controls render order within that group.
// Tags not listed here auto-appear in an implicit "Other" group at the end.
export const TAG_GROUPS: Record<string, string[]> = {
  Meta: [
    "learning-in-public",
    "research",
    "tips",
    "short",
    "paper-club",
    "MSCS",
  ],
  "AI/ML": [
    "machine-learning",
    "deep-learning",
    "supervised-learning",
    "unsupervised-learning",
    "reinforcement-learning",
    "NLP",
    "large-language-models",
    "transformer",
    "inference",
    "AI-alignment",
    "mechanistic-interpretability",
    "reasoning",
    "optimization",
    "data-science",
    "information-retrieval",
    "python",
    "pyTorch",
    "GPU",
    "CUDA",
    "computer-vision",
    "generative-models",
    "HDDA",
    "neural-networks",
  ],
  Systems: [
    "computer-science",
    "software-engineering",
    "algorithms",
    "parallel-algorithms",
    "computer-architecture",
    "compilers",
    "simulation",
    "search",
    "distributed-systems",
    "operating-systems",
    "multithreading",
    "socket-programming",
    "RPC",
    "IPC",
    "c",
    "c++",
    "go",
    "node",
    "typescript",
    "git",
    "GIOS",
  ],
};
